### ISSUE TITLE
bison error

### ISSUE THREAD

**Issue by hazardpl** [nimble-code/Modex#1]
bison -v -d gram.y
bison report an error:
gram.y: conflicts: 48 shift/reduce, 23 reduce/reduce
win_bison: C:\Modex-master\Src\data/m4sugar/m4sugar.m4: cannot open: No such fil
e or directory

**Comment by nimble-code** [comment]
I've no idea what the m4sugar.m4 files is all about -- it's not part of the distribution.
the format looks odd as well, with some forward and backward slashes mixed.
i assume you're executing this on a windows system (given the filename)?
a call to 'make' on my system (windows, with cygwin), proceeds normally as follows:
bison -v -d gram.y
gram.y: warning: 48 shift/reduce conflicts [-Wconflicts-sr]
gram.y: warning: 23 reduce/reduce conflicts [-Wconflicts-rr]
mv gram.tab.c gram.c
mv gram.tab.h gram.h
gcc  -g   -c -o heap.o heap.c
gcc  -g   -c -o nmetab.o nmetab.c
gcc  -g   -c -o symtab.o symtab.c
gcc  -g   -c -o modex.o modex.c
gcc  -g   -c -o xtract.o xtract.c
gcc  -g   -c -o token.o token.c
gcc  -g   -c -o tree.o tree.c
gcc  -g   -c -o treestk.o treestk.c
flex lexer.l
mv lex.yy.c lexer.c
gcc  -g   -c -o lexer.o lexer.c
gcc  -g   -c -o gram.o gram.c
gcc  -g   -c -o dflow.o dflow.c
gcc  -g   -c -o prnttree.o prnttree.c
gcc  -g   -c -o modex_pp.o modex_pp.c
gcc  -g   -c -o ps_graph.o ps_graph.c
gcc  -o modex heap.o nmetab.o symtab.o modex.o xtract.o token.o tree.o treestk.o lexer.o gram.o dflow.o prnttree.o modex_pp.o ps_graph.o -lm
(and there's no Src/data directory there)

**Comment by hazardpl** [comment]
thanks!
the problem is solved
step1  my bison is not install correct , re-install bison will be OK;
step2  I modified  pram.y line50 
/* The next line makes the parser re-entrant. */
//%define api.pure full 
%pure_parser
but,I dont know why. : )
