### ISSUE TITLE
Repository is outdated

### ISSUE THREAD

**Issue by rillig** [nimble-code/Modex#12]
https://spinroot.com/modex/MANUAL.html has the "Modex 2.8 User Guide", while this repository has 2.6. The repository should either be updated to the current version or be archived.

https://spinroot.com/modex/ is at version 2.10, that's another inconsistency.

Background: I'd like to fix a few typos in the manual, but I don't want to waste time editing an outdated version of the manual.

**Comment by nimble-code** [comment]
as best as I can see, the github version is 2.11
there shouldn't be too much difference with 2.8 as described in the manual

**Comment by rillig** [comment]
From what I can see, [the GitHub version of the manual states 2.6](https://github.com/nimble-code/Modex/blob/9aee55a8de602d3914b676e8463e9e3061a8632e/Manual/MANUAL.html#L3), which I guess is older than the version published on https://spinroot.com/. So I wonder when and how the website is synchronized with the repository, and how changes from the website are ported back into the repository, as there should be only a single source of truth.
