### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by zhang-cell** [nimble-code/Modex#4]
Dear author:
I use the substitute keyword to analyze the mutex in case 6_ lock
(&amp;count_ The mapping rules are as follows:
Substitute	c_ code{mutex_ lock(&amp;count_ lock);}	atomic { count_ lock == 0 -> count_ lock = 1 }
Substitute	c_ code{mutex_ unlock(&amp;count_ lock);}	count_ lock = 0
However, I found that atomic {count} was not generated in the generated Promela model_ lock == 0 -> count_ Lock = 1} and count_ lock = 0
Instead: C_ code { mutex_ lock((&amp;( now.count_ Lock));}; and
c_ code { mutex_ unlock((&amp;( now.count_ lock))); };
Do you know what the problem is?

**Comment by nimble-code** [comment]
is it a problem?  does the code verify correctly?

**Comment by zhang-cell** [comment]
This should be mapped to atomic {count_ lock == 0 -> count_  Lock = 1} and count_ lock = 0，instead of using c_code the default mapping method

**Comment by zhang-cell** [comment]
And in the manual under the mdoex file abp.prx The file defines two mapping tables. But only 'abp_rcv 'realizes mapping relation, 'abp_ snd' does not use the mapping relationship in the. PRX file, but uses the default mapping relationship. Why

**Comment by nimble-code** [comment]
ok

**Comment by zhang-cell** [comment]
Hello,does Promela contain operations to stop threads?

**Comment by nimble-code** [comment]
no it doesn't
