### ISSUE TITLE
install

### ISSUE THREAD

**Issue by zhang-cell** [nimble-code/Modex#5]
When I download modex in cygwin, it displays:“fatal error: gram.tab.h: No such file or directory
compilation terminated.”do you know why?thanks...

**Comment by nimble-code** [comment]
when you compile?
you'll nee yacc, or an equivalent eg byacc, to generate the parser files (gram.tab.c and gran.tab.h)

**Comment by kikishao** [comment]
> 



> When I download modex in cygwin, it displays:“fatal error: gram.tab.h: No such file or directory compilation terminated.”do you know why?thanks...

I installed byacc, but still encountered the same problem, how did you solve it in the end?

**Comment by nimble-code** [comment]
those two files are created by yacc  (or byacc or bison, if you have those installed instead of yacc.
bison -v -d gram.y
